name: NIX Solutions Ltd.
description: "NIX Solutions Ltd is outsourcing IT company located in Kharkiv, Ukraine. It provides custom software development: web, mobile, and desktop"
avatar: https://avatars0.githubusercontent.com/u/4631052?v=3&s=200
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: nixsolutions
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:

disqus:

google_analytics: true

url: http://nixsolutions.github.io

baseurl: ""

permalink: "/_pages/"

# The release of Jekyll Now that you're using
version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

include: ["_pages"]

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
  - CNAME
